#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdarg.h>
#include "applet_api.h"

extern int stdout_init(void);

static uint32_t sys_get_tick(void) {
    static uint32_t tick = 0;
    return tick++;
}

static void sys_delay_ms(uint32_t ms) {
    volatile uint32_t count = ms * 1000;
    while (count--) {
        __asm volatile ("nop");
    }
}

static void sys_putc(char c) {
    putchar(c);
}

static void sys_print(const char* fmt, ...) {
    va_list args;
    va_start(args, fmt);
    vprintf(fmt, args);
    va_end(args);
}

static void* sys_malloc(size_t size) {
    (void)size;
    return NULL;
}

static void sys_free(void* ptr) {
    (void)ptr;
}

static void* sys_realloc(void* ptr, size_t size) {
    (void)ptr;
    (void)size;
    return NULL;
}

static const applet_api_t g_applet_api = {
    .version = 1,
    .print = sys_print,
    .putc = sys_putc,
    .get_tick = sys_get_tick,
    .delay_ms = sys_delay_ms,
    .malloc = sys_malloc,
    .free = sys_free,
    .realloc = sys_realloc,
};

#define APPLET_MAX_SIZE 4096
static uint8_t applet_memory[APPLET_MAX_SIZE] __attribute__((aligned(4)));

static int load_applet(const uint8_t* data, size_t size) {
    if (size > APPLET_MAX_SIZE) {
        printf("Error: Applet too large (%zu > %d bytes)\n", size, APPLET_MAX_SIZE);
        return -1;
    }
    
    printf("Loading applet (%zu bytes)...\n", size);
    memcpy(applet_memory, data, size);
    
    applet_header_t* header = (applet_header_t*)applet_memory;
    
    if (header->magic != APPLET_MAGIC) {
        printf("Error: Invalid applet magic (expected 0x%08lX, got 0x%08lX)\n", 
               (uint32_t)APPLET_MAGIC, (uint32_t)header->magic);
        return -1;
    }
    
    if (header->version != APPLET_VERSION) {
        printf("Error: Unsupported applet version (expected %d, got %lu)\n", 
               APPLET_VERSION, (unsigned long)header->version);
        return -1;
    }
    
    printf("Applet magic: 0x%08lX OK\n", (uint32_t)header->magic);
    printf("Applet version: %lu\n", (unsigned long)header->version);
    
    const uint32_t link_base = APPLET_LINK_ADDR;
    uint32_t load_base = (uint32_t)applet_memory;
    int64_t delta = (int64_t)load_base - (int64_t)link_base;
    
    printf("Link base: 0x%08lX\n", (unsigned long)link_base);
    printf("Load base: 0x%08lX\n", (unsigned long)load_base);
    printf("Delta: %ld\n", (long)delta);
    
    // Relocate entry point
    uint32_t entry_link = (uint32_t)header->entry;
    uint32_t entry_load = (int64_t)entry_link + (int64_t)delta;
    header->entry = (uint32_t (*)(const struct applet_api*, void*))entry_load;
    
    // Relocate name pointer
    uint32_t name_link = (uint32_t)header->name;
    uint32_t name_load = (int64_t)name_link + (int64_t)delta;
    header->name = (const char*)name_load;
    
    printf("Entry (link): 0x%08lX\n", (unsigned long)entry_link);
    printf("Entry (load): 0x%08lX\n", (unsigned long)entry_load);
    printf("Name (link): 0x%08lX\n", (unsigned long)name_link);
    printf("Name (load): 0x%08lX\n", (unsigned long)name_load);
    printf("Name: %s\n", header->name);
    
    printf("Executing applet...\n");
    printf("=====================================\n");
    
    uint32_t result = header->entry(&g_applet_api, NULL);
    
    printf("=====================================\n");
    printf("Applet returned: %lu\n", (unsigned long)result);
    
    return 0;
}

// Embedded applet binary (generated by Makefile)
extern unsigned char out_applet_loader_applets_sample_applet_bin[];
extern const unsigned int out_applet_loader_applets_sample_applet_bin_len;

extern unsigned char out_applet_loader_applets_counter_applet_bin[];
extern const unsigned int out_applet_loader_applets_counter_applet_bin_len;

int main(void) {
    stdout_init();
    
    printf("\n========================================\n");
    printf("MPS2-AN385 Minimal Applet Loader\n");
    printf("========================================\n\n");
    
    load_applet(out_applet_loader_applets_sample_applet_bin, out_applet_loader_applets_sample_applet_bin_len);
    load_applet(out_applet_loader_applets_counter_applet_bin, out_applet_loader_applets_counter_applet_bin_len);
    
    while (1) {
        __asm volatile ("wfi");
    }
}
