/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        mavenLocal()  // Required to pick up locally published plugin
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
}


dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = "multi-project"

val projects = listOf(
    "helloworld" to "app/helloworld/",
    "helloworld-kotlin" to "app/helloworld-kotlin/",
    "helloworld-kotlin-coroutine" to "app/helloworld-kotlin-coroutine/",
    "helloworld-jna" to "app/helloworld-jna/",
    "calc-aes" to "app/crypto/calc-aes/",
    "zero-padding-3des-cbc" to "app/crypto/zero-padding-3des-cbc/",
    "selfsign-cert" to "app/crypto/selfsign-cert/",
    "rsa-op" to "app/crypto/rsa-op/",
    "aes-ctr-demo" to "app/crypto/aes-ctr-demo/",
    "block-cipher-mac" to "app/crypto/block-cipher-mac/",
    "annotation-processor-lib" to "app/annotation-processor-demo/lib/",
    "annotation-processor-demo" to "app/annotation-processor-demo/demo/"
)

// See: https://docs.gradle.org/8.14.2/userguide/multi_project_builds.html#multi_project_layout
projects.forEach { (name, path) ->
    include(":$name")
    project(":$name").projectDir = File(path)
}
