default:
    just --list

# configure cmake project (run once)
configure:
    cmake -B build -DCMAKE_BUILD_TYPE=Debug

# build a specific target (e.g. just build src/uv_version)
build target:
    cmake --build build --target `basename {{target}}`

# build + run a specific target (e.g. just run src/uv_version)
run target: (build target)
    ./build/{{target}}/`basename {{target}}`

# build all targets
build-all:
    cmake --build build

# remove build directory
clean:
    rm -rf build
