; add `ansible_password=xxx` same line after `ansible_user=xxxx`
; or --ask-pass for cmdline arg
[server]
PUT.YOUR.IP.HERE ansible_user=root

[local]
# will not use ssh.
localhost ansible_connection=local
