; add `ansible_password=xxx` same line after `ansible_user=xxxx`
; or --ask-pass for cmdline arg
[server]
PUT.YOUR.IP.HERE ansible_user=root

; See: https://docs.ansible.com/projects/ansible/latest/inventory/implicit_localhost.html
; we dont need localhost explict, already exist by default
; and not in group all
;
; [local]
; # will not use ssh.
; localhost ansible_connection=local
