/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.example.greeter.Greeter;


public class App {
    public static void main(String[] args) {
        Greeter greeter = new Greeter();
        System.out.println(greeter.sayHello("HelloWorld"));
    }
}
