/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'Blinky+Simulator' 
 * Target:  'Simulator' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "CMSDK_CM3.h"

/* Keil::CMSIS Driver:USART@1.0.3 */
#define RTE_Drivers_USART
/* Keil::Compiler&ARM Compiler:I/O:STDOUT&User@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */


#endif /* RTE_COMPONENTS_H */

