/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    private static final String TDES_KEY_HEX = "1C2F7849077DF96C662BA0AF927BE4365FCCF73A9E334A5E";
    private static final String TDES_IV_HEX = "0000000000000000";
    private static final int BLOCK_SIZE = 8;
    private static final String ALGORITHM = "DESede";

    private static Cipher getCipher(int mode, String keyHex) throws Exception {
        byte[] key = hexToBytes(keyHex);
        byte[] iv = hexToBytes(TDES_IV_HEX);
        SecretKeySpec keySpec = new SecretKeySpec(key, ALGORITHM);
        IvParameterSpec ivSpec = new IvParameterSpec(iv);
        Cipher cipher = Cipher.getInstance("DESede/CBC/NoPadding");
        cipher.init(mode, keySpec, ivSpec);
        return cipher;
    }

    private static byte[] hexToBytes(String hex) {
        int len = hex.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4)
                    + Character.digit(hex.charAt(i + 1), 16));
        }
        return data;
    }

    private static byte[] zeroPad(byte[] data) {
        int padLen = BLOCK_SIZE - (data.length % BLOCK_SIZE);
        if (padLen == BLOCK_SIZE) {
            padLen = 0;
        }
        byte[] padded = new byte[data.length + padLen];
        System.arraycopy(data, 0, padded, 0, data.length);
        return padded;
    }

    private static byte[] zeroUnpad(byte[] data) {
        int len = data.length;
        while (len > 0 && data[len - 1] == 0) {
            len--;
        }
        byte[] result = new byte[len];
        System.arraycopy(data, 0, result, 0, len);
        return result;
    }

    public static void encrypt(Path inPath, Path outPath, String keyHex) throws Exception {
        byte[] plaintext = Files.readAllBytes(inPath);
        byte[] padded = zeroPad(plaintext);
        Cipher cipher = getCipher(Cipher.ENCRYPT_MODE, keyHex);
        byte[] ciphertext = cipher.doFinal(padded);
        Files.write(outPath, ciphertext);
        System.out.printf("Encrypted %s -> %s (%d -> %d bytes)%n", inPath, outPath, plaintext.length, ciphertext.length);
    }

    public static void decrypt(Path inPath, Path outPath, String keyHex) throws Exception {
        byte[] ciphertext = Files.readAllBytes(inPath);
        Cipher cipher = getCipher(Cipher.DECRYPT_MODE, keyHex);
        byte[] padded = cipher.doFinal(ciphertext);
        byte[] plaintext = zeroUnpad(padded);
        Files.write(outPath, plaintext);
        System.out.printf("Decrypted %s -> %s (%d -> %d bytes)%n", inPath, outPath, ciphertext.length, plaintext.length);
    }

    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            printHelp();
            System.exit(1);
        }

        String command = args[0];
        String keyHex = TDES_KEY_HEX;
        Path input = null;
        Path output = null;

        for (int i = 1; i < args.length; i++) {
            switch (args[i]) {
                case "-i":
                case "--input":
                    input = Paths.get(args[++i]);
                    break;
                case "-o":
                case "--output":
                    output = Paths.get(args[++i]);
                    break;
                case "-k":
                case "--key":
                    keyHex = args[++i];
                    break;
                default:
                    System.err.println("Unknown option: " + args[i]);
                    printHelp();
                    System.exit(1);
            }
        }

        if (input == null || output == null) {
            System.err.println("Input and output paths are required.");
            printHelp();
            System.exit(1);
        }

        if ("encrypt".equals(command)) {
            encrypt(input, output, keyHex);
        } else if ("decrypt".equals(command)) {
            decrypt(input, output, keyHex);
        } else {
            printHelp();
            System.exit(1);
        }
    }

    private static void printHelp() {
        System.out.println("Usage: java org.example.App <encrypt|decrypt> -i <input> -o <output> [-k <key_hex>]");
    }
}
