/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private static final String TDES_KEY_HEX = "1C2F7849077DF96C662BA0AF927BE4365FCCF73A9E334A5E";

    @Test
    void testEncryptDecrypt(@TempDir Path tempDir) throws Exception {
        Path input = tempDir.resolve("input.txt");
        Path encrypted = tempDir.resolve("encrypted.bin");
        Path decrypted = tempDir.resolve("decrypted.txt");

        String content = "Hello World!";
        Files.writeString(input, content);

        App.encrypt(input, encrypted, TDES_KEY_HEX);
        assertTrue(Files.exists(encrypted));

        App.decrypt(encrypted, decrypted, TDES_KEY_HEX);
        assertEquals(content, Files.readString(decrypted));
    }

    @Test
    void testEncryptDecryptEmpty(@TempDir Path tempDir) throws Exception {
        Path input = tempDir.resolve("empty.txt");
        Path encrypted = tempDir.resolve("empty.bin");
        Path decrypted = tempDir.resolve("empty_dec.txt");

        Files.write(input, new byte[0]);

        App.encrypt(input, encrypted, TDES_KEY_HEX);
        App.decrypt(encrypted, decrypted, TDES_KEY_HEX);
        assertEquals(0, Files.size(decrypted));
    }

    @Test
    void testEncryptDecryptWithTrailingZeros(@TempDir Path tempDir) throws Exception {
        // Note: zero padding strips all trailing zeros, so content ending in \0 loses them
        Path input = tempDir.resolve("zeros.bin");
        Path encrypted = tempDir.resolve("zeros_enc.bin");
        Path decrypted = tempDir.resolve("zeros_dec.bin");

        byte[] data = new byte[]{0x01, 0x02, 0x00, 0x00};
        Files.write(input, data);

        App.encrypt(input, encrypted, TDES_KEY_HEX);
        App.decrypt(encrypted, decrypted, TDES_KEY_HEX);

        byte[] result = Files.readAllBytes(decrypted);
        // trailing zeros are lost
        assertArrayEquals(new byte[]{0x01, 0x02}, result);
    }

    @Test
    void testEncryptDecryptBlockSizeMultiple(@TempDir Path tempDir) throws Exception {
        Path input = tempDir.resolve("block.txt");
        Path encrypted = tempDir.resolve("block.bin");
        Path decrypted = tempDir.resolve("block_dec.txt");

        String content = "ABCDEFGH"; // exactly 8 bytes
        Files.writeString(input, content);

        App.encrypt(input, encrypted, TDES_KEY_HEX);
        App.decrypt(encrypted, decrypted, TDES_KEY_HEX);
        assertEquals(content, Files.readString(decrypted));
    }
}
