
west := "uvx --with jsonschema --with pyelftools --with anytree west"

run:
    just build -t run
tracecmake:
    # after -- is cmake args
    just build -- --trace

build *args:
    {{west}} build -b mps2/an385 demo/helloworld/ {{args}}




