/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    fun getGreeting(): String {
        return "Hello World!"
    }
}

fun main() {
    println(App().getGreeting())
}
